//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.sql_Query
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Graphic_cardsEntities : DbContext
    {
        public Graphic_cardsEntities()
            : base("name=Graphic_cardsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sql_Arch_cost_avg_Result> sql_Arch_cost_avg(string arch_Name)
        {
            var arch_NameParameter = arch_Name != null ?
                new ObjectParameter("Arch_Name", arch_Name) :
                new ObjectParameter("Arch_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_Arch_cost_avg_Result>("sql_Arch_cost_avg", arch_NameParameter);
        }
    
        public virtual ObjectResult<sql_Manufact_energy_between_Result> sql_Manufact_energy_between(string manufact_name, Nullable<int> min_Energy, Nullable<int> max_Energy)
        {
            var manufact_nameParameter = manufact_name != null ?
                new ObjectParameter("Manufact_name", manufact_name) :
                new ObjectParameter("Manufact_name", typeof(string));
    
            var min_EnergyParameter = min_Energy.HasValue ?
                new ObjectParameter("Min_Energy", min_Energy) :
                new ObjectParameter("Min_Energy", typeof(int));
    
            var max_EnergyParameter = max_Energy.HasValue ?
                new ObjectParameter("Max_Energy", max_Energy) :
                new ObjectParameter("Max_Energy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_Manufact_energy_between_Result>("sql_Manufact_energy_between", manufact_nameParameter, min_EnergyParameter, max_EnergyParameter);
        }
    
        public virtual ObjectResult<sql_Manufact_memory_each_year_Result> sql_Manufact_memory_each_year(string manufact_Name)
        {
            var manufact_NameParameter = manufact_Name != null ?
                new ObjectParameter("Manufact_Name", manufact_Name) :
                new ObjectParameter("Manufact_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_Manufact_memory_each_year_Result>("sql_Manufact_memory_each_year", manufact_NameParameter);
        }
    
        public virtual ObjectResult<sql_Memory_between_and_year_Result> sql_Memory_between_and_year(Nullable<int> year, Nullable<int> min_memory, Nullable<int> max_memory)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var min_memoryParameter = min_memory.HasValue ?
                new ObjectParameter("Min_memory", min_memory) :
                new ObjectParameter("Min_memory", typeof(int));
    
            var max_memoryParameter = max_memory.HasValue ?
                new ObjectParameter("Max_memory", max_memory) :
                new ObjectParameter("Max_memory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_Memory_between_and_year_Result>("sql_Memory_between_and_year", yearParameter, min_memoryParameter, max_memoryParameter);
        }
    }
}
